/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frames;

import controle.controleacesso;
import framesTabela.SAIDA;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Bibia
 */
public class cadastro extends javax.swing.JFrame {

    controleacesso c = new controleacesso();
    SimpleDateFormat form = new SimpleDateFormat("dd/MM/yyyy");
    String Adm = null;

    /**
     * Creates new form cadastro
     */
    public cadastro() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Nome = new javax.swing.JTextField();
        D_admissao = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        Htrabalhada = new javax.swing.JFormattedTextField();
        VHtrabalhada = new javax.swing.JFormattedTextField();
        label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Gabriola", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Cadastro de Funcionários");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 340, 50));

        jButton1.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("Clique para começar ");
        jButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 200, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/71ca9a5da2232e499f44b7d510d385b5.jpg"))); // NOI18N
        jLabel2.setAutoscrolls(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 430));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 440));

        jPanel2.setMinimumSize(new java.awt.Dimension(500, 370));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 300));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        Nome.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeActionPerformed(evt);
            }
        });
        Nome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NomeKeyPressed(evt);
            }
        });
        jPanel2.add(Nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, 30));

        D_admissao.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        try {
            D_admissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        D_admissao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                D_admissaoKeyPressed(evt);
            }
        });
        jPanel2.add(D_admissao, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 210, 30));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Data de admissão:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Valor da hora trabalhada: ");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Horas trabalhadas: ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, -1, -1));

        jButton2.setText("x");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton2.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 50, 20));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("IMPRIMIR");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 70, -1));

        jButton4.setText("SALVAR");
        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 80, -1));

        Htrabalhada.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Htrabalhada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        Htrabalhada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HtrabalhadaActionPerformed(evt);
            }
        });
        Htrabalhada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                HtrabalhadaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                HtrabalhadaKeyTyped(evt);
            }
        });
        jPanel2.add(Htrabalhada, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 210, 30));

        VHtrabalhada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                VHtrabalhadaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VHtrabalhadaKeyTyped(evt);
            }
        });
        jPanel2.add(VHtrabalhada, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 210, 30));

        label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/60c39e8dd446877c80527a540f143abf.jpg"))); // NOI18N
        jPanel2.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -110, 810, 590));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SAIDA s = new SAIDA(c);
        s.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed


        String nome = Nome.getText();
        Adm = D_admissao.getText();
        String VHT = VHtrabalhada.getText();
        String HT = Htrabalhada.getText();
        funcionario f = new funcionario();
        if (nome.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor, informe seu nome");
            label.setForeground(Color.red);
            Nome.setForeground(Color.red);
            Nome.requestFocus();
            
        } else if (Adm.isBlank() || D_admissao.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Por favor, informe sua data de admissao");
            jLabel4.setForeground(Color.red);
            D_admissao.setForeground(Color.red);
            D_admissao.requestFocus();
        } else if (VHT.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor, informe o valor da hora trabalhada");
            jLabel5.setForeground(Color.red);
            VHtrabalhada.setForeground(Color.red);
            VHtrabalhada.requestFocus();
        } else if (HT.isBlank()) {
            JOptionPane.showMessageDialog(null, "Por favor, informe quantas horas trabalhou");
            jLabel6.setForeground(Color.red);
            Htrabalhada.setForeground(Color.red);
            Htrabalhada.requestFocus();
        }   else{
        try {    
                form.setLenient(false);
                Date Admissao = form.parse(Adm);
                f.setDataAdmissao(Admissao);
                f.setNome(nome);
                f.setValor_horas(Float.parseFloat(VHT));
                f.setHoras_trabalhadas(Float.parseFloat(HT));
            } catch (ParseException ex) {
                JOptionPane.showMessageDialog(null, "Data Inválida!");
                jLabel4.setForeground(Color.red);
                D_admissao.setForeground(Color.red);
                D_admissao.requestFocus();
            }
            int tempoEmpresa = f.calcularTempoempresa();
            float salario = f.calcularSalario();
            
            JOptionPane.showMessageDialog(null,"Nome: " + f.getNome()
                    + "\ndata de admissão: " + f.getDataAdmissao()
                    + "\nvalor da hora trabalhada: " + f.getValor_horas()
                    + "\nhoras trabalhadas: " + f.getHoras_trabalhadas()
                    + "\nTempo na empresa: " + tempoEmpresa
                    + "\nSalario: " + salario);

            if (c.Salvar(f)) {
                JOptionPane.showMessageDialog(null, "cadastro realizado");
                Nome.setText(" ");
                D_admissao.setValue(null);
                VHtrabalhada.setText(" ");
                Htrabalhada.setText(" ");
                Nome.requestFocus(); 
            } else {
                JOptionPane.showMessageDialog(null, "erro");
            }
        
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void NomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NomeKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            D_admissao.requestFocus();
        }
    }//GEN-LAST:event_NomeKeyPressed

    private void D_admissaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_D_admissaoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            VHtrabalhada.requestFocus();
        }
    }//GEN-LAST:event_D_admissaoKeyPressed

    private void HtrabalhadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HtrabalhadaKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            Nome.requestFocus();
        }
    }//GEN-LAST:event_HtrabalhadaKeyPressed

    private void VHtrabalhadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VHtrabalhadaKeyPressed
        
    }//GEN-LAST:event_VHtrabalhadaKeyPressed

    private void VHtrabalhadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VHtrabalhadaKeyTyped
       String caracteres = "0123456789.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
    }
    }//GEN-LAST:event_VHtrabalhadaKeyTyped

    private void HtrabalhadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HtrabalhadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HtrabalhadaActionPerformed

    private void HtrabalhadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_HtrabalhadaKeyTyped
         String caracteres = "0123456789.";
        if(!caracteres.contains(evt.getKeyChar()+"")){
        evt.consume();
    }
    }//GEN-LAST:event_HtrabalhadaKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel2.setVisible(true);
        jPanel1.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastro().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField D_admissao;
    private javax.swing.JFormattedTextField Htrabalhada;
    private javax.swing.JTextField Nome;
    private javax.swing.JFormattedTextField VHtrabalhada;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel label;
    // End of variables declaration//GEN-END:variables
}
